### ISSUE TITLE
Survey Form text alignment

### ISSUE THREAD

**Issue by enorar** [lsecities/urbangovernance-wp-theme#3]
It seems like the text is not perfectly aligned on the right hand side of the page. Would it be possible to fix this?

**Comment by hotzeplotz** [comment]
@enorar, not sure i understand this - paragraphs are supposed to be aligned to the left and ragged to the right, which is what i see on this page. if you mean that lines should all stretch to the right margin as in justified text, this is widely avoided on the web due to readability issues. if i misunderstood your note, please let me know.

**Comment by enorar** [comment]
OK no problem!
