### ISSUE TITLE
Landing page link to the partners website

### ISSUE THREAD

**Issue by enorar** [lsecities/urbangovernance-wp-theme#4]
It seems like it is not possible to click on the partners' logos and directly access their website, would it be possible to insert a link to the LSE Cities, UN Habitat, UCLG and MacArthur Foundation websites?

**Comment by hotzeplotz** [comment]
links:
* UN Habitat http://unhabitat.org/
* UCLG http://www.uclg.org/
* Mac Arthur Foundation http://www.macarthur.org/

**Comment by hotzeplotz** [comment]
ok, this is now fixed.

**Comment by enorar** [comment]
Thanks!!

**Comment by enorar** [comment]
It looks like the links are working on all the pages but not on the landing page? (sorry I might be double checking too quickly!)

**Comment by enorar** [comment]
It seems like the links open directly and replace the urbangovernance website, would it be possible to make sure that when people click, the link opens in a new tab?

**Comment by hotzeplotz** [comment]
@enorar you're right - it turns out that the footer in the home page is generated from a different bit of code. i'll check tomorrow how to best fix this (ideally by removing the code duplication and using the bit of code to which i added the links today).

in terms of opening in another window/tab, i would strongly discourage this. the common reasoning is that we don't want users to leave our site, but whether in a new tab or not, if a visitor is more interested in the site they click through to, they're not much more likely to get back to the previous site and if they wish to, they can use the browser back button. they can still open the link in a new tab if they wish (e.g. by clicking on the middle mouse button), whereas opening by default in a new tab doesn't leave this choice. on mobile devices or older computers, having many tabs open can also slow down the browser. there are some good cases to open by default in a new tab, but apart from those it's not generally considered best practice.

**Comment by enorar** [comment]
Oh I see! No problem - I didn't know that was the rational but it makes perfect sense!

**Comment by hotzeplotz** [comment]
all footers now share the same code (as of ca560c5dd7b8ab19bb5e6374b6c7bf9feba58d58)
